#!/usr/bin/env python3
import sys
from os import environ

environ['DISPLAY'] = ':0'

from pyautogui import press, hotkey

times = 1

if len(sys.argv) > 2:
    times = int(sys.argv[2])

if len(sys.argv) > 1 and '+' in sys.argv[1]:
    for i in range(times):
        hotkey(*sys.argv[1].split('+'))

elif len(sys.argv) > 1:
    for i in range(times):
        press(sys.argv[1])
else:
    print('requires one argument: name of the key (optional second: number of presses)')
